### ISSUE TITLE
Should it work in any terminal? It doesn't seem to work in my case

### ISSUE THREAD

**Issue by edvard-munch** [mbarkhau/pretty-traceback#10]
Tried to see pretty-tracebak in action in some of my scripts, doesn't seem to work.
Doing import and install() in entry points of my scripts. It imports the module, but traceback stays the same

Done the same thing in Python shell, just to show the screenshot here
Should it work in Python shell btw?

![Screenshot from 2024-01-05 14-18-48](https://github.com/mbarkhau/pretty-traceback/assets/26732881/f3b29747-5bf9-4202-83a6-4edbf10eede1)

**Comment by mbarkhau** [comment]
I don't see why it wouldn't work and yes that code should work in principle. Does it work on your machine using a terminal other than Tilix?
