### ISSUE TITLE
Does pretty-traceback not work with decorators?

### ISSUE THREAD

**Issue by ubless607** [mbarkhau/pretty-traceback#11]
![image](https://github.com/mbarkhau/pretty-traceback/assets/5417257/fa8bc996-6426-4e25-9170-ac0e3ae8a678)

Hello,

I tried the example code posted at https://github.com/mbarkhau/pretty-traceback/issues/2 and the library worked fine.
However, trying to code with decorators doesn't seem to be working.

Thanks in advance.

**Comment by mbarkhau** [comment]
I'm not sure what's going on here, but I'm quite sure it has nothing to do with the fact of anything being a decorator. Possibly Hydra adds it's own stacktrace handling.
