### ISSUE TITLE
TERM colours and different output.

### ISSUE THREAD

**Issue by kierun** [mbarkhau/pretty-traceback#2]
I might be doing something wrong but this is what I see:

![screenshot](https://user-images.githubusercontent.com/3079575/108879398-23088700-75f9-11eb-924d-24e9a88255bb.png)

The script:

```python
#!/usr/bin/env python3
"""CRASH!"""

#import stackprinter
#stackprinter.set_excepthook(style='darkbg2')  # for jupyter notebooks try style='lightbg'

try:
    import pretty_traceback
    #pretty_traceback.install(envvar='ENABLE_PRETTY_TRACEBACK')
    pretty_traceback.install()
except ImportError:
    pass    # no need to fail because of missing dev dependency


def main():
    1 / 0


if __name__ == "__main__":
    main()
```

**Comment by mbarkhau** [comment]
Can you remove the `try except ImportError`, just to make sure the lib is actually imported?

**Comment by kierun** [comment]
![screenshot](https://user-images.githubusercontent.com/3079575/108901468-d0d45f80-7612-11eb-9426-f2d0d292ca30.png)

Yes, it appears to be correct.

However, look at what happens when I create a virtual environment. How about that? Looking into what crazy thing is happening there… I will update.

BTW,  big fan of GitS SAC here too! :+1:

**Comment by kierun** [comment]
A typical error between keyboard and floor…

I have `BETTER_EXCEPTIONS=1` set in my shell by default. Thus, it did what it was always supposed to do. Mystery solved!

I suspect the `TERM` between `tmux` and `tmux-256` is a colorama thing. I have had nothing but trouble with it. Personally, I would move to rich and if I had time, I would do a PR for you. Sadly, I am snowed under. My apologies.

**Comment by mbarkhau** [comment]
> I suspect the TERM between tmux and tmux-256 is a colorama thing.

Not sure what you mean by this.

**Comment by kierun** [comment]
> > I suspect the TERM between tmux and tmux-256 is a colorama thing.
> 
> Not sure what you mean by this.

Still working late in the evening and realised I was talking about a bug in better-exceptions… Ignore it.

**Comment by kierun** [comment]
Anyway, it's all working fine. Thank you for your module and my apologies for the noise…

**Comment by mbarkhau** [comment]
No worries. Happy hacking.

**Comment by kierun** [comment]
Thank you!
