### ISSUE TITLE
`LoggingFormatterMixin` calls `os.terminal_size()` which doesn't work when app is not running in TTY

### ISSUE THREAD

**Issue by tadams42** [mbarkhau/pretty-traceback#9]
Hi! 

I'm using `pretty-traceback` as part of my application logging. App is deployed inside of a docker container which means app's process is not running in TTY. 

When my loggers call `formatException` from:

```python
class LoggingFormatterMixin(object):

    def formatException(self, ei):
        _, exc_value, traceback = ei
        return exc_to_traceback_str(exc_value, traceback, color=True)
```

I get `"stty: standard input: Not a tty"` message. This is because of following call chain:

```
exc_to_traceback_str() 
    --> _get_terminal_width() 
        --> os.get_terminal_size()
```

Current workaround for me is adding environment variable `COLUMNS`. It effectively prevents call to `os.get_terminal_size`. 

This is fine, but is not perfect :blush: .

I would like to avoid adding `COLUMNS` env variable and would like to instead do this through code. Something like this would work for me, but any other solution that let's me somehow avoid call to `os.get_terminal_size()` is also fine:

```diff
- def exc_to_traceback_str(exc_value, traceback, color=False):
+ def exc_to_traceback_str(exc_value, traceback, color=False, columns=None):
```

- when `columns is not None`, use that, ignore `os.environ["COLUMNS"]` and don't call `os.get_terminal_size()`
- when `columns is None` keep current behavior

**Comment by mbarkhau** [comment]
Can you verify that the problem goes away, if guard the import by `sys.stdout.isatty()` ?

**Comment by mbarkhau** [comment]
I hope the latest release fixes this.

**Comment by tadams42** [comment]
Yep, `2023.1020` fixes it. Thnx!
